### ISSUE TITLE
failed to send analytics

### ISSUE THREAD

**Issue by Orthus** [NPException42/GameAnalyticsAPI#7] opened 2016-02-24 01:12 UTC
Hey NPE,

Just shooting this error I noted in a clients service:

[de.npe.gameanalytics.EventHandler$RESTHelper:sendData:209]: Failed to send analytics event data. Result of attempt: ok | Authentication hash used: aa505b4994af166bb9cf48a5b5c53c59 | Data sent: [{"install_publisher":"1.8.0_45-b14","install_site":"server","install_campaign":"2.6.32-504.12.2.el6.x86_64","install_adgroup":"amd64","install_ad":"Linux","install_keyword":"server","user_id":"server8f2b19ba-8f0f-4e38-95cf-a4f791957974","session_id":"1456276073039","build":"unspecified"}]

**Comment by NPException** [comment] 2016-02-24 06:34
Do you get that
- `Failed to send analytics event data. Result of attempt: ok`

often?

What I am expecting there as a result from the GA service is the JSON `{"status":"ok"}`, not just `ok`. I suspect GA may have changed their services behaviour slightly, to ignore the accepted response type. (Which I set as `application/json`)

I'll do a quick fix for that case, but that will only reach end users once the mods that use GA-API update to the fixed versionl.

**Comment by Orthus** [comment] 2016-02-24 07:13
Looking into the server's console, it appears to occur every 10 secs.

**Comment by Mickimoo** [comment] 2016-02-24 07:18
I have the same issue, whats your mod list we might be able to find which one is causing the spam.

[01:38:47] [GA-DataSendThread/INFO] [STDERR]: [de.npe.gameanalytics.EventHandler$RESTHelper:sendData:209]: Failed to send analytics event data. Result of attempt: ok | Authentication hash used: 7dfc94c25713c8c90c7f3a71e6c0584c | Data sent: [{"install_publisher":"1.8.0_72-b15","install_site":"server","install_campaign":"3.14.32-xxxx-grs-ipv6-64","install_adgroup":"amd64","install_ad":"Linux","install_keyword":"server","user_id":"server754189a4-5dbd-44d1-a0c3-fee55f3115e3","session_id":"1456136355905","build":"591"}]

**Comment by NPException** [comment] 2016-02-24 07:30
>  it appears to occur every 10 secs.

Yeah that is the regular sending interval. So it is definitely a derp on GameAnalytics side, as they are ignoring my requested response type. Since when does this happen? Did it only start recently?

> I have the same issue, whats your mod list we might be able to find which one is causing the spam.

I personally only know 2 mods for sure which currently use my GA-API. The first one being _DimensionalPockets_, the second being _FFS - Fancy Fluid Storage_ by @Lordmau5. There are most likely other mods that use GA-API as well though.

Keep in mind that the issue is caused by a derp of GA itself and may very well be fixed on their end soon. I'll contact them about the issue. Do not throw mods out of your packs because of GA's hickups (yet). :)

If you have Dimensional Pockets in your mod list, there is a config setting to stop it from sending data to GameAnalytics: `MAY_COLLECT_ANONYMOUS_USAGE_DATA`
Just set that to `false`, and the spam should stop. If it doesn't, that means that another mod is using the GA-API as well.

**Comment by Mickimoo** [comment] 2016-02-24 07:37
I can confirm that I have Fancy Fluid Storage, and there isn't a config for it there ;)

**Comment by NPException** [comment] 2016-02-24 07:39
Actually, an easy workaround for you to get rid of the spam is to deactivate Minecrafts snooper setting.

GA-API by default will only send data to GameAnalytics if MCs snooper setting is enabled. As long as all mods that use GA-API do respect that, it should solve the spam issue for now. :)

But in the name of all lovers of usage statistics, I suggest to wait with that for a couple of days. Maybe GA fixes their derp. :D

**Comment by NPException** [comment] 2016-02-24 08:05
Since when do you guys get those messages? Just recently?

**Comment by NPException** [comment] 2016-02-24 08:18
Quick update: I looked into their documentation, which still says that their server will respond with JSON. (And not plaintext, like it actually does atm)

I filed a support ticket with the issue and will inform you about their response as soon as I get one.

**Comment by Mickimoo** [comment] 2016-02-24 08:33
I updated my pack about 3 days ago, I noticed it today when I went to update it again

**Comment by NPException** [comment] 2016-03-04 20:10
Quick update: I received an answer from Christian from GA-Support yesterday. He told me that they could not find any change on their end, and everything seems normal.

What is a little weird is that Christian wrote that their server response is the usual

```
{[{<<"status">>,<<"ok">>}]}
```

, while what I expect is the response mentioned in their [API documentation](https://go.gameanalytics.com/game/19988/content/sdk?page=rest&step=5):

```
{"status": "ok"}
```

Yet what I actually got (and probably still get) is just a plaintext "ok".

I wrote back asking about that immediately and hope to have a satisfying answer soon.

**Comment by NPException** [comment] 2016-03-04 20:16
Let me drag @shadowfacts into the conversation as he seems to have the same problem.

Can anyone of you confirm that the issue still exists?

**Comment by shadowfacts** [comment] 2016-03-04 21:55
Yep, this is happening for me. [This](https://gist.github.com/shadowfacts/34bda07fa8a6930c41ae) is from the Project Ozone MC log when I was playing yesterday and getting the exact same error message.

**Comment by NPException** [comment] 2016-03-04 22:00
@shadowfacts do you have either Dimensional Pockets or Fancy Fluid Storage in your modpack?

**Comment by shadowfacts** [comment] 2016-03-04 22:01
Neither are present in Project Ozone.

**Comment by NPException** [comment] 2016-03-04 22:07
Do you know which mods in your pack are using GA-API?

**Comment by shadowfacts** [comment] 2016-03-04 22:22
Aura Cascade (version 557)

**Comment by Mickimoo** [comment] 2016-03-05 00:56
@shadowfacts Would you mind asking the pack author to update AuraCascade. That version is 2 releases behind :)

I can confirm that I am no longer receiving the spam as auracascade has updated, I am assuming that was the mod that had caused us trouble.

**Comment by AdlyTempleton** [comment] 2016-03-05 02:22
My Aura Cascade GA account was disabled, probably the problems you're experiencing. (was causing some spam problems)

**Comment by NPException** [comment] 2016-03-05 08:58
@pixlepix now that's strange. Did GA give you any specific reason why it disabled your account?

**Comment by NPException** [comment] 2016-03-05 09:14
@pixlepix: I see that you have your GA keys publicly available in your Aura Cascade repo. I'd highly reccomend removing them from the repo and not commiting them. While they will still be retrievable from the compiled mod for anyone who want's to spam GA with that credentials, it takes a lot more effort than just looking them up in the repo. :)

This is how I have it in Dimensional Pockets Repo f.e.: https://github.com/NPException/Dimensional-Pockets/blob/eeff154e157dabdc30e564432423d4882d04f327/java/net/gtn/dimensionalpocket/common/core/utils/DPAnalytics.java#L25

I only ever replace them with the actual keys when compiling the mod. (I guess one could even adjust the build.gradle to do replacements there.)

**Comment by lionmaiden** [comment] 2016-12-09 19:16
I keep getting this message on my console. It is spamming my console.

[Server] WARN Failed to send analytics event data. Result of attempt: ok | Authentication hash used: 2278d6836b2f33d4bc71a812448ee95b | Data sent: [{"install_publisher":"1.8.0_112-b15","install_site":"server","install_campaign":"3.14.32-xxxx-grs-ipv6-64","install_adgroup":"amd64","install_ad":"Linux","install_keyword":"server","user_id":"server5f70ef6c-542b-458d-86c4-c78bfdba4d99","session_id":"1481231630152","build":"unspecified"}]

I do have aura in the pack i'm using and I did disable snooper.
Is there another way I can stop this spam?
Thanks

**Comment by NPException** [comment] 2016-12-09 21:13
If you set `snooper-enabled=false` in your *server.properties* and it is still trying to send data, then that means that Aura Cascade is not using my provided MCSimpleAnalytics base class, and I take no responsibility for AC not respecting the snooper setting.

I don't know which version of AC you are using, but I know that the currently available source code for has the analytics stuff commented out entirely. So maybe you need to upgrade your version of AC?

**Comment by lionmaiden** [comment] 2016-12-10 15:05
I'm using Aura Cascade (version 557).

**Comment by NPException** [comment] 2016-12-10 15:14
@AdlyTempleton: is there a way to disable the analytics with a config within AC 557?

**Comment by m0nkm0nk** [comment] 2016-12-12 08:48
Look for Aura.cfg

```
    # Sends anonymous reports on usage. Automatically disaled if snooper settings are disabled [default: true]
    B:analytics=false


```

**Comment by lionmaiden** [comment] 2016-12-12 16:33
I tried that, it still came up with the same error. I think it might be the
pack I'm using. I'm reading about a lot of people who have put this pack on
a server are having problems.

Thanks

**Comment by NPException** [comment] 2017-03-09 20:56
I added some sort of "log spam protection" to the [updated](https://github.com/NPException/GameAnalyticsAPI/commit/cfc4ee05a9278783d6933cdfdafd83e4aad0fa84) version 1.3 of GA API.

With this new version, if sending the analytics data fails, the sending will be suspended for some time (30 seconds at first). If the sending still fails after a suspension, the suspension time is doubled, up to a maximum of 32 minutes.

I think a log message every 32 minutes for the whole day in a worst case scenario ist okay-ish.

I would consider this ticket closed, unless there is new information you are able to provide @lionmaiden?

**Closed as completed** 2017-03-09 20:57 UTC
